apiVersion: v1
kind: Namespace
metadata:
  name: techne-execution
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: techne-controller-remote
  namespace: techne-execution
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: techne-execution
  namespace: techne-execution
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: techne-controller-execution
  namespace: techne-execution
rules:
  - apiGroups: [batch]
    resources: [jobs]
    verbs: [create, get, list, watch, delete]
  - apiGroups: ['']
    resources: [pods]
    verbs: [get, list, watch]
  - apiGroups: ['']
    resources: [pods/log]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: techne-controller-execution
  namespace: techne-execution
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: techne-controller-execution
subjects:
  - kind: ServiceAccount
    name: techne-controller-remote
    namespace: techne-execution
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-execution-network
  namespace: techne-execution
spec:
  podSelector: {}
  policyTypes: [Ingress, Egress]
