apiVersion: v1
kind: ServiceAccount
metadata:
  name: techne-controller
  namespace: techne-controller
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: techne-execution
  namespace: techne-execution
automountServiceAccountToken: false
